print("     |---------------------------------------|")    #32
print("     |  PYPHONE 2.10.0                       |")  
print("     |                                       |")
username = input("     |Enter Your Username:")
if username == "FMN": 
    password = input("     |Enter Your Password:")
    if password == "1471":
      print("     |Your PyPhone is unlocked               |")
      print("     |                                       |")
      print("     |Current IP: 217.181.21.225             |")
      print("     |UPDATE: Pyphone:beta is now vaulted.   |")
      print("     |Please update to v1.10 or higher.      |")
      print("     |                                       |")
      print("     |                                       |")
      print("     |                                       |")
      print("     |                                       |")
      print("     |                                       |")
      direction = input("     |Page Direction:") 
if direction == "F":
      print("     |PAGE 2 - CONTACTS                      |")
      print("     |                                       |")
      print("     |1-                                     |")
      print("     |Pyphone Premium User Helpline          |")
      print("     |Email: premiumsupport.pyphone@gmail.com|")
      print("     |Phone: 01634 323711                    |")
      print("     |Note: Pyphone Premium User Helpline is |")
      print("     |only available to premium members of   |")
      print("     |the pyphone community.                 |")
      print("     |                                       |")
      print("     |2- EMPTY CONTACT SLOT                  |")
      print("     |Email:                                 |")
      print("     |Phone:                                 |")
      print("     |Note:                                  |")
      print("     |                                       |")
      print("     |3- EMPTY CONTACT SLOT                  |")
      print("     |Email:                                 |")
      print("     |Phone:                                 |")
      print("     |Note:                                  |")
      print("     |                                       |")
      print("     |                                       |")
      direction = input("     |Page Direction:") 
if direction == "F":
      print("     |PAGE 3 - VAULT                         |")
      print("     |                                       |")
      print("     |                                       |")
      vault = input("     |Enter the password to your PyVault:")
if vault == "axcF4RHk":
      print("     |Welcome to your PyVault. You have 2 items in the vault:")
      print("     |---------------------------------------|")
      print("     |---------------------------------------|")
      print("     | ITEM 1                                |")    
      print("     |---------------------------------------|")
      print("     | ITEM 2                                | ")
      print("     |---------------------------------------|")
      print("     |---------------------------------------|") 
